#' calc_inefficient_gRNA_logfc
#'
#' Calculates the ratio of normalized counts for inefficient sgRNA PAM-proximal sequences relative to all guides (taking the median of each).
#'
#' @param logfc A data frame of log2 fold change data for each sample in the study (samples as columns, gRNAs as rows) as generated by `fgcQC::calc_log2_fold_change_gRNAs`.
#' @param library A data frame containing the library file in which the first column gives the sgRNA sequence and the second column gives the sgRNA ID.
#'
#' @return A data frame containing two columns: `log2FC_GCC_ratio` and `log2FC_TT_ratio`.
#' @importFrom dplyr mutate filter rowwise
#' @references Graf, R. et al. (2019) sgRNA sequence motifs blocking efficient CRISPR/Cas9-mediated gene editing. Cell Rep 26: 1098-1103.
#' @export
calc_inefficient_gRNA_logfc <- function(logfc, library){
  tryCatch({
    library %<>%
      fgcQC::extract_proximal_4bases_PAM() %>%
      dplyr::filter(V2 %in% logfc$sgRNA)
    logfc %<>%
      dplyr::filter(sgRNA %in% library$V2) %>%
      dplyr::mutate(proximal_4bases_pam = library$proximal_4bases_pam[match(sgRNA, V2)])
    ret <- data.frame(log2FC_GCC_ratio = median(logfc$log2FC[logfc$proximal_4bases_pam == "GCC"], na.rm=T)/median(logfc$log2FC, na.rm=T),
                      log2FC_TT_ratio = median(logfc$log2FC[logfc$proximal_4bases_pam == "TT"], na.rm=T)/median(logfc$log2FC, na.rm=T))
  },
  error = function(e) stop(paste("unable to calculate inefficient gRNA logFC ratios:",e))
  )
  return(ret)
}
