#' calc_log2_fold_change_genes
#'
#' Calculates median log2 fold changes for genes (taking as input output from `calc_log2_fold_change_gRNAs`).
#'
#' @param logf A data frame of log2 fold change data generated by `fgcQC::calc_log2_fold_change_gRNAs`.
#'
#' @return A data frame with a column named `log2FC_gene`.
#'
#' @importFrom dplyr mutate group_by ungroup
#' @importFrom magrittr %<>%
#' @export
calc_log2_fold_change_genes <- function(logf){
  if(!"log2FC" %in% colnames(logf))
    stop("expecting a column named 'log2FC' in input")
  if(!"gene" %in% colnames(logf))
    stop("expecting a column named 'gene' in input")

  logf %<>%
    dplyr::group_by(gene) %>%
    dplyr::mutate(log2FC_gene = median(log2FC, na.rm=T)) %>%
    dplyr::ungroup()
  return(logf)
}
