#' calc_dcorr_GC_content_logfc
#'
#' Calculates the distance correlation between the log2 fold change and the GC content of sgRNAs in a given library.
#'
#' @param logfc A data frame of log2 fold change data for each sample in the study (samples as columns, gRNAs as rows) as generated by `fgcQC::calc_log2_fold_change_gRNAs`.
#' @param library A data frame containing the library file in which the first column gives the sgRNA sequence and the second column gives the sgRNA ID.
#'
#' @return A data frame with a `SampleName` column and a `distcorr_GC_content_logfc` column.
#' @importFrom dplyr filter
#' @importFrom energy dcor2d
#' @importFrom magrittr %<>%
#' @references Szekely, G.J., Rizzo, M.L., and Bakirov, N.K. (2007), Measuring and Testing Dependence by Correlation of Distances, Annals of Statistics, Vol. 35 No. 6, pp. 2769-2794.
#' @export
calc_dcorr_GC_content_logfc <- function(logfc, library){
  tryCatch({
    library %<>%
      fgcQC::calc_GC_percent_library() %>%
      dplyr::filter(V2 %in% logfc$sgRNA)
    logfc %<>%
      dplyr::filter(sgRNA %in% library$V2)
    ret <- data.frame(distcorr_GC_content_logfc = energy::dcor2d(logfc$log2FC,
                                                                library$GC_percent[match(logfc$sgRNA, library$V2)],
                                                                type = "U"))
  },
  error = function(e) stop(paste("unable to calculate dist corr for GC vs logFC:",e))
  )
  return(ret)
}
